name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build Android APK
        run: ./gradlew :composeApp:assembleDebug

      - name: Upload Android APK
        uses: actions/upload-artifact@v6
        with:
          name: android-apk
          path: composeApp/build/outputs/apk/debug/*.apk
